version: '3'
services:
  parken-nest-db:
    container_name: parken-nest-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=parken_nest'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'